<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Influence Diagnostics • HLMdiag</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Influence Diagnostics">
<meta property="og:description" content="HLMdiag">
<meta property="og:image" content="/logo.png">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">HLMdiag</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.4.0.9000</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/hlm_resid.html">Residual Diagnostics</a>
    </li>
    <li>
      <a href="../articles/influence_diagnostics.html">Influence Diagnostics</a>
    </li>
    <li>
      <a href="../articles/jss_update.html">Updated JSS code</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/aloy/HLMdiag/">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="influence_diagnostics_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Influence Diagnostics</h1>
                        <h4 class="author">Jaylin Lowe, Jack Moran, Adam Loy</h4>
            
            <h4 class="date">2021-01-16</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/aloy/HLMdiag/blob/master/vignettes/influence_diagnostics.Rmd"><code>vignettes/influence_diagnostics.Rmd</code></a></small>
      <div class="hidden name"><code>influence_diagnostics.Rmd</code></div>

    </div>

    
    
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/aloy/HLMdiag">HLMdiag</a></span><span class="op">)</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; Attaching package: 'HLMdiag'</span>
<span class="co">#&gt; The following object is masked from 'package:stats':</span>
<span class="co">#&gt; </span>
<span class="co">#&gt;     covratio</span></code></pre></div>
<div id="overview" class="section level1">
<h1 class="hasAnchor">
<a href="#overview" class="anchor"></a>Overview</h1>
<p>The <code>HLMdiag</code> package provides functionality to examine diagnostics for hierarchical linear models, including residuals values and influence diagnostics. This vignette aims to:</p>
<ul>
<li>inform users how to use the new function <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code>, which provides any easy way to obtain multiple influence diagnostics in one tibble</li>
<li>inform users how to use the new function <code><a href="../reference/hlm_augment.lmerMod.html">hlm_augment()</a></code>, which combines <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> and <code><a href="../reference/hlm_resid.default.html">hlm_resid()</a></code> to return influence diagnostics and residuals</li>
<li>introduce new functionality for <code>lme</code> created from the <code>nlme</code> package</li>
<li>compare the differences between Cook’s distances values returned by <code>HLMdiag</code> and those returned by the <code>lme4</code> and <code>car</code> packages</li>
</ul>
<div id="hlm_influence-function" class="section level2">
<h2 class="hasAnchor">
<a href="#hlm_influence-function" class="anchor"></a><code>hlm_influence()</code> function</h2>
<div id="introduction" class="section level3">
<h3 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h3>
<p>The <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> function provides a wrapper that returns influence diagnostics appended to the original model frame. It is useful for assessing the influence of individual observations, or groups of observations, and can also be used with <code><a href="../reference/dotplot_diag.html">dotplot_diag()</a></code> to visually explore the influence diagnostics. The diagnostics returned by <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> include Cook’s distance, MDFFITS, covariance trace (covtrace), covariance ratio (covratio), leverage, and relative variance change (RVC).</p>
<p>Cook’s distance and MDFFITS both measure the distance between fixed effects estimated from the full data set and those obtained from the reduced data set. For Cook’s distance, the change in parameter estimates is scaled by the estimated covariance matrix of the original parameter estimates, while MDFFITS scales this change by the estimated covariance matrix of the deletion estimates. The covariance trace and covariance ratio both measure how precision is affected by the deletion of a particular observation or group of observations <em>i</em>. Covariance trace is a measure of the ratio between the covariance matrices with and without unit <em>i</em> to the identity matrix, while covariance ratio is a comparison of the two covariance matrices with and without unit <em>i</em> using their determinants. Relative variance change (RVC) is a measurement of the ratio of estimates of the <em>l</em> th variance component with and without unit <em>i</em>. The final influence diagnostic returned by <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code>, leverage, is the rate of change in the predicted response with respect to the observed response. For a full explanation of these influence diagnostics, including formulas, please refer to Loy and Hofmann (2014).</p>
<p>To explore the functionality of <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code>, we will use the data set <code>classroom</code> (<strong>West et. al, 2014</strong>). The data set consists of 1,190 observations of students. Students are grouped within classes, which are nested within schools. There are 312 distinct classes nested within 107 schools.</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"classroom"</span>, package <span class="op">=</span> <span class="st">"WWGbook"</span><span class="op">)</span></code></pre></div>
<pre><code>#&gt; # A tibble: 1,190 x 12
#&gt;      sex minority mathkind mathgain   ses yearstea mathknow housepov mathprep
#&gt;    &lt;int&gt;    &lt;int&gt;    &lt;int&gt;    &lt;int&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
#&gt;  1     1        1      448       32  0.46        1    NA       0.082     2   
#&gt;  2     0        1      460      109 -0.27        1    NA       0.082     2   
#&gt;  3     1        1      511       56 -0.03        1    NA       0.082     2   
#&gt;  4     0        1      449       83 -0.38        2    -0.11    0.082     3.25
#&gt;  5     0        1      425       53 -0.03        2    -0.11    0.082     3.25
#&gt;  6     1        1      450       65  0.76        2    -0.11    0.082     3.25
#&gt;  7     0        1      452       51 -0.03        2    -0.11    0.082     3.25
#&gt;  8     0        1      443       66  0.2         2    -0.11    0.082     3.25
#&gt;  9     1        1      422       88  0.64        2    -0.11    0.082     3.25
#&gt; 10     0        1      480       -7  0.13        2    -0.11    0.082     3.25
#&gt;    classid schoolid childid
#&gt;      &lt;int&gt;    &lt;int&gt;   &lt;int&gt;
#&gt;  1     160        1       1
#&gt;  2     160        1       2
#&gt;  3     160        1       3
#&gt;  4     217        1       4
#&gt;  5     217        1       5
#&gt;  6     217        1       6
#&gt;  7     217        1       7
#&gt;  8     217        1       8
#&gt;  9     217        1       9
#&gt; 10     217        1      10
#&gt; # … with 1,180 more rows</code></pre>
<p>We will fit a simple three-level hierarchical linear model using the <code>lme4</code> package:</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">class.lmer</span> <span class="op">&lt;-</span> <span class="fu">lme4</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">mathgain</span> <span class="op">~</span> <span class="va">mathkind</span> <span class="op">+</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">minority</span> <span class="op">+</span> <span class="va">ses</span> <span class="op">+</span> <span class="va">housepov</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span><span class="op">|</span><span class="va">schoolid</span><span class="op">/</span><span class="va">classid</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">classroom</span><span class="op">)</span></code></pre></div>
</div>
<div id="obtain-influence-diagnostics-at-different-levels-with-level" class="section level3">
<h3 class="hasAnchor">
<a href="#obtain-influence-diagnostics-at-different-levels-with-level" class="anchor"></a>Obtain influence diagnostics at different levels with <code>level</code>
</h3>
<p><code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> calculates influence diagnostics for individual cases, or larger groups. For example, to obtain a tibble with influence diagnostics for all 1,190 students we use the following:</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">infl</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/hlm_influence.default.html">hlm_influence</a></span><span class="op">(</span><span class="va">class.lmer</span>, level <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></code></pre></div>
<pre><code>#&gt; # A tibble: 1,190 x 14
#&gt;       id mathgain mathkind   sex minority   ses housepov schoolid classid
#&gt;    &lt;int&gt;    &lt;int&gt;    &lt;int&gt; &lt;int&gt;    &lt;int&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;int&gt;   &lt;int&gt;
#&gt;  1     1       32      448     1        1  0.46    0.082        1     160
#&gt;  2     2      109      460     0        1 -0.27    0.082        1     160
#&gt;  3     3       56      511     1        1 -0.03    0.082        1     160
#&gt;  4     4       83      449     0        1 -0.38    0.082        1     217
#&gt;  5     5       53      425     0        1 -0.03    0.082        1     217
#&gt;  6     6       65      450     1        1  0.76    0.082        1     217
#&gt;  7     7       51      452     0        1 -0.03    0.082        1     217
#&gt;  8     8       66      443     0        1  0.2     0.082        1     217
#&gt;  9     9       88      422     1        1  0.64    0.082        1     217
#&gt; 10    10       -7      480     0        1  0.13    0.082        1     217
#&gt;          cooksd      mdffits covtrace covratio leverage.overall
#&gt;           &lt;dbl&gt;        &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;            &lt;dbl&gt;
#&gt;  1 0.00106      0.00106       0.00289     1.00           0.121 
#&gt;  2 0.00143      0.00143       0.00246     1.00           0.121 
#&gt;  3 0.000336     0.000335      0.00378     1.00           0.122 
#&gt;  4 0.000225     0.000225      0.00169     1.00           0.0780
#&gt;  5 0.000173     0.000172      0.00178     1.00           0.0780
#&gt;  6 0.000000807  0.000000804   0.00321     1.00           0.0794
#&gt;  7 0.0000233    0.0000233     0.00113     1.00           0.0775
#&gt;  8 0.0000000504 0.0000000504  0.00120     1.00           0.0775
#&gt;  9 0.000130     0.000129      0.00401     1.00           0.0801
#&gt; 10 0.00108      0.00108       0.00147     1.00           0.0778
#&gt; # … with 1,180 more rows</code></pre>
<p>Note that the parameter used to select individual observations is now called <code>level</code>, not <code>group</code>. Previous versions of <code>HLMdiag</code> used the group parameter for influence diagnostics, where <code>group = NULL</code> was the default, and users could choose to delete groups instead by setting <code>group</code> equal to level names. As of <code>HLMdiag</code> version 0.4.0, <code>group</code> has been replaced by <code>level</code>. <code>level</code> defaults to <code>level = 1</code> which deletes individual observations, exactly how <code>group = NULL</code> used to work.</p>
<p>The resulting tibble can be used along with <code><a href="../reference/dotplot_diag.html">dotplot_diag()</a></code> to identify potentially influential observations using either an internal cutoff of 3*IQR or a user-specified cutoff. For example, the plot shown below reveals and labels all observations above the internally calculated cutoff for Cook’s distance.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/dotplot_diag.html">dotplot_diag</a></span><span class="op">(</span><span class="va">infl</span><span class="op">$</span><span class="va">cooksd</span>, name <span class="op">=</span> <span class="st">"cooks.distance"</span>, cutoff <span class="op">=</span> <span class="st">"internal"</span><span class="op">)</span></code></pre></div>
<p>The plot illustrates that there are many observations with a Cook’s distance value above the internally calculated cutoff. <code><a href="../reference/dotplot_diag.html">dotplot_diag()</a></code> labels the top 5, which is difficult to see in this case. Rather than investigate all observations above the cutoff, we may be interested in the observations with the highest Cook’s distance values. The tibble returned by <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> provides an easy way to do this when used with the <code>arrange()</code> function from <code>dplyr</code>.</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tb1</span> <span class="op">&lt;-</span> <span class="va">infl</span> <span class="op">%&gt;%</span>
  <span class="fu">arrange</span><span class="op">(</span><span class="fu">desc</span><span class="op">(</span><span class="va">cooksd</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>#&gt; # A tibble: 1,190 x 14
#&gt;       id mathgain mathkind   sex minority   ses housepov schoolid classid cooksd
#&gt;    &lt;int&gt;    &lt;int&gt;    &lt;int&gt; &lt;int&gt;    &lt;int&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;int&gt;   &lt;int&gt;  &lt;dbl&gt;
#&gt;  1   539      253      290     0        1 -0.4     0.257       47      82 0.0536
#&gt;  2    41     -110      434     0        1 -0.37    0.365        4     179 0.0265
#&gt;  3  1078      203      290     1        1 -0.32    0.067       95     144 0.0256
#&gt;  4   664      -84      629     1        0  2.33    0.17        62      22 0.0245
#&gt;  5   312      138      542     1        0  2.27    0.05        27     104 0.0221
#&gt;  6   754      218      368     0        1 -1.14    0.43        70     152 0.0202
#&gt;  7   337      197      290     1        1 -0.46    0.214       28     203 0.0194
#&gt;  8   723      214      290     1        1 -0.67    0.209       68     244 0.0187
#&gt;  9   812      147      510     0        0 -0.47    0.367       75      42 0.0148
#&gt; 10  1146       11      376     0        1  0.62    0.126      102      44 0.0132
#&gt;    mdffits covtrace covratio leverage.overall
#&gt;      &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;            &lt;dbl&gt;
#&gt;  1  0.0527  0.0172      1.02           0.112 
#&gt;  2  0.0264  0.00406     1.00           0.143 
#&gt;  3  0.0250  0.0250      1.03           0.147 
#&gt;  4  0.0242  0.0125      1.01           0.0869
#&gt;  5  0.0219  0.00988     1.01           0.0919
#&gt;  6  0.0200  0.00702     1.01           0.0896
#&gt;  7  0.0190  0.0198      1.02           0.147 
#&gt;  8  0.0183  0.0195      1.02           0.155 
#&gt;  9  0.0147  0.00797     1.01           0.0722
#&gt; 10  0.0131  0.00825     1.01           0.0962
#&gt; # … with 1,180 more rows</code></pre>
<p>There does not appear to be a clear pattern among students who have relatively higher Cook’s distance values; they do not tend to be from a particular school or class. In order to investigate these observations further, one could look to summary statistics for the different explanatory variables. Additionally, a similar analysis could be done with the other influence diagnostics provided in the tibble from <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code>.</p>
<p>In addition to identifying influential observations, it may also be useful to identify influential groups. The <code>level</code> parameter in <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> can be used for this purpose. For example, we can obtain influence diagnostics for each class:</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">infl.classes</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/hlm_influence.default.html">hlm_influence</a></span><span class="op">(</span><span class="va">class.lmer</span>, level <span class="op">=</span> <span class="st">"classid:schoolid"</span><span class="op">)</span></code></pre></div>
<pre><code>#&gt; # A tibble: 312 x 6
#&gt;    `classid:schoolid`   cooksd  mdffits covtrace covratio leverage.overall
#&gt;    &lt;fct&gt;                 &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;            &lt;dbl&gt;
#&gt;  1 160:1              0.00224  0.00224   0.00990     1.01           0.0980
#&gt;  2 217:1              0.00133  0.00131   0.0238      1.02           0.128 
#&gt;  3 197:2              0.00323  0.00320   0.0106      1.01           0.123 
#&gt;  4 211:2              0.00724  0.00719   0.0202      1.02           0.0891
#&gt;  5 307:2              0.00346  0.00343   0.0197      1.02           0.152 
#&gt;  6 11:3               0.00116  0.00115   0.0141      1.01           0.0960
#&gt;  7 137:3              0.000873 0.000868  0.0131      1.01           0.150 
#&gt;  8 145:3              0.00517  0.00515   0.0248      1.02           0.0983
#&gt;  9 228:3              0.000479 0.000478  0.00797     1.01           0.126 
#&gt; 10 48:4               0.00371  0.00367   0.0212      1.02           0.134 
#&gt; # … with 302 more rows</code></pre>
<p>Note that the <code>level</code> parameter is set as <code>classid:schoolid</code>, not <code>classid</code>. The level parameter should be specified as found in <code>model@flist</code> for lmerMod objects. For three level models, this usually takes the form of “level2:level3”, where level2 is the name of the second level variable, and level3 is the name of the third level variable.</p>
<p>Using <code><a href="../reference/dotplot_diag.html">dotplot_diag()</a></code> again with one of the columns from the resulting tibble of <code>hlm_influence</code> reveals that class 218 has a relatively high Cook’s distance value.</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/dotplot_diag.html">dotplot_diag</a></span><span class="op">(</span><span class="va">infl.classes</span><span class="op">$</span><span class="va">cooksd</span>, name <span class="op">=</span> <span class="st">"cooks.distance"</span>, cutoff <span class="op">=</span> <span class="st">"internal"</span><span class="op">)</span></code></pre></div>
<p>We can repeat a similar analysis to flag influential schools.</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">infl.schools</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/hlm_influence.default.html">hlm_influence</a></span><span class="op">(</span><span class="va">class.lmer</span>, level <span class="op">=</span> <span class="st">"schoolid"</span><span class="op">)</span></code></pre></div>
<pre><code>#&gt; # A tibble: 107 x 6
#&gt;    schoolid   cooksd  mdffits covtrace covratio leverage.overall
#&gt;    &lt;fct&gt;       &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;            &lt;dbl&gt;
#&gt;  1 1        0.000561 0.000557   0.0381     1.04           0.0901
#&gt;  2 2        0.00681  0.00672    0.0554     1.06           0.115 
#&gt;  3 3        0.0343   0.0333     0.0723     1.07           0.108 
#&gt;  4 4        0.0248   0.0246     0.0360     1.04           0.125 
#&gt;  5 5        0.00224  0.00223    0.0583     1.06           0.0998
#&gt;  6 6        0.0109   0.0107     0.0690     1.07           0.104 
#&gt;  7 7        0.00576  0.00560    0.0785     1.08           0.108 
#&gt;  8 8        0.0121   0.0118     0.0785     1.08           0.0926
#&gt;  9 9        0.00624  0.00590    0.0793     1.08           0.141 
#&gt; 10 10       0.00848  0.00826    0.0723     1.07           0.0928
#&gt; # … with 97 more rows</code></pre>
<p>Similarly, we use <code>dotplot_diag</code> to visually represent the differences. In this case, there are only four observations above the cutoff, so we set <code>modify = "dotplot"</code> in order to better visualize the influential observations. <code>modify = "dotplot"</code> works well when there are a relatively small number of observations above the cutoff.</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/dotplot_diag.html">dotplot_diag</a></span><span class="op">(</span><span class="va">infl.schools</span><span class="op">$</span><span class="va">cooksd</span>, name <span class="op">=</span> <span class="st">"cooks.distance"</span>, cutoff <span class="op">=</span> <span class="st">"internal"</span>, modify <span class="op">=</span> <span class="st">"dotplot"</span><span class="op">)</span></code></pre></div>
<p>The plot reveals that schools 68, 75, 70, and 27 have relatively high Cook’s distance values.</p>
</div>
<div id="investigate-deletion-of-specific-observations-or-groups-with-delete" class="section level3">
<h3 class="hasAnchor">
<a href="#investigate-deletion-of-specific-observations-or-groups-with-delete" class="anchor"></a>Investigate deletion of specific observations or groups with <code>delete</code>
</h3>
<p>The <code>delete</code> parameter allows the user to calculate influence diagnostics for a specified group of observations, or group factor level. For example, influence diagnostics for the influential schools flagged above (68, 75, 70, and 27) can be calculated as shown below, deleting all four schools at once:</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/hlm_influence.default.html">hlm_influence</a></span><span class="op">(</span><span class="va">class.lmer</span>, level <span class="op">=</span> <span class="st">"schoolid"</span>, delete <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"27"</span>, <span class="st">"70"</span>, <span class="st">"75"</span>, <span class="st">"68"</span><span class="op">)</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 1 x 4</span>
<span class="co">#&gt;   cooksd mdffits covtrace covratio</span>
<span class="co">#&gt;    &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;</span>
<span class="co">#&gt; 1  0.238   0.222    0.370     1.43</span></code></pre></div>
<p>Note that in this case, <code>delete</code> is specified as a character vector consisting of the school ID’s of interest. <code>delete</code> can also be set as a numeric vector of indices; in this case, setting <code>delete</code> to the row numbers of all students in the data frame who attend schools 68, 75, 70, or 27 would be equivalent to the line above.</p>
</div>
<div id="select-different-types-of-leverage-with-leverage-argument" class="section level3">
<h3 class="hasAnchor">
<a href="#select-different-types-of-leverage-with-leverage-argument" class="anchor"></a>Select different types of leverage with <code>leverage</code> argument</h3>
<p>In the previous examples, <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> only returned overall leverage. However, <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> also allows for other types of leverage, including the leverage corresponding to the fixed effects, the leverage corresponding to the random effects as proposed by Demidenko and Stukel (2005), and the unconfounded leverage corresponding to the random effects proposed by Nobre and Singer (2011). These types of leverage are referred to as <code>fixef</code>, <code>ranef</code>, and <code>ranef.uc</code>, respectively.</p>
<p>None of our observations are flagged for high leverage when looking only at overall leverage:</p>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/dotplot_diag.html">dotplot_diag</a></span><span class="op">(</span><span class="va">infl</span><span class="op">$</span><span class="va">leverage.overall</span>, name <span class="op">=</span> <span class="st">"leverage"</span>, cutoff <span class="op">=</span> <span class="st">"internal"</span><span class="op">)</span></code></pre></div>
<p>However, we can obtain the other types of leverage as follows:</p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">infl2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/hlm_influence.default.html">hlm_influence</a></span><span class="op">(</span><span class="va">class.lmer</span>, level <span class="op">=</span> <span class="fl">1</span>, leverage <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"overall"</span>, <span class="st">"fixef"</span>, <span class="st">"ranef"</span>, <span class="st">"ranef.uc"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>This example illustrates how to select all four types of leverage, but any one or more may also be selected.</p>
<p>We can then use <code><a href="../reference/dotplot_diag.html">dotplot_diag()</a></code> with one of the new leverage columns to investigate outlier for that type of leverage.</p>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/dotplot_diag.html">dotplot_diag</a></span><span class="op">(</span><span class="va">infl2</span><span class="op">$</span><span class="va">leverage.fixef</span>, name <span class="op">=</span> <span class="st">"leverage"</span>, cutoff <span class="op">=</span> <span class="st">"internal"</span>, modify <span class="op">=</span> <span class="st">"dotplot"</span><span class="op">)</span></code></pre></div>
<p>However, further analysis reveals that several observations have high leverage when considering only the leverage corresponding to the fixed effects.</p>
</div>
<div id="choose-between-approximations-or-full-refits-with-approx" class="section level3">
<h3 class="hasAnchor">
<a href="#choose-between-approximations-or-full-refits-with-approx" class="anchor"></a>Choose between approximations or full refits with <code>approx</code>
</h3>
<p><code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> defaults to calculating influence diagnostics based off a one step approximation (<strong>Christensen et.al 1992</strong>; <strong>Shi and Chen 2008</strong>; <strong>Zewotir 2008</strong>). However, the <code>approx</code> parameter allows the user to calculate influence diagnostics based off a full refit of the data using <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code>. For example, if we wished to calculate influence diagnostics for each school by fully refitting the model each time, we could use:</p>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">infl3</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/hlm_influence.default.html">hlm_influence</a></span><span class="op">(</span><span class="va">class.lmer</span>, level <span class="op">=</span> <span class="st">"schoolid"</span>, approx <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<pre><code>#&gt; # A tibble: 107 x 9
#&gt;    schoolid   cooksd  mdffits covtrace covratio rvc.sigma2   rvc.D11  rvc.D22
#&gt;    &lt;fct&gt;       &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
#&gt;  1 1        0.000642 0.000639   0.0565    1.06    -0.00262  0.0154    0.0183 
#&gt;  2 2        0.00684  0.00676    0.0423    1.04    -0.00409  0.0161   -0.00403
#&gt;  3 3        0.0389   0.0386     0.0256    0.973    0.00299  0.000124 -0.0952 
#&gt;  4 4        0.0249   0.0253     0.0971    0.906   -0.0315  -0.0293    0.0174 
#&gt;  5 5        0.00222  0.00221    0.0691    1.07    -0.00229  0.0160    0.00997
#&gt;  6 6        0.0111   0.0109     0.0671    1.07     0.00443  0.00323  -0.0198 
#&gt;  7 7        0.00564  0.00546    0.0970    1.10     0.00436  0.0230   -0.0119 
#&gt;  8 8        0.0117   0.0115     0.0653    1.07    -0.00744 -0.0804    0.0574 
#&gt;  9 9        0.00634  0.00598    0.0922    1.09     0.00313  0.00326  -0.00216
#&gt; 10 10       0.00816  0.00790    0.109     1.11     0.00796  0.0220   -0.00935
#&gt;    leverage.overall
#&gt;               &lt;dbl&gt;
#&gt;  1           0.0901
#&gt;  2           0.115 
#&gt;  3           0.108 
#&gt;  4           0.125 
#&gt;  5           0.0998
#&gt;  6           0.104 
#&gt;  7           0.108 
#&gt;  8           0.0926
#&gt;  9           0.141 
#&gt; 10           0.0928
#&gt; # … with 97 more rows</code></pre>
<p>In most cases, using the default of <code>approx = TRUE</code> is sufficient for influence analysis. Setting <code>approx = FALSE</code> also takes much longer than the default setting since the model must be refit each time with each group or observation deleted. However, the full refit method also allows for relative variance change (RVC) to be returned. If this is desired, <code>approx = FALSE</code> should be used.</p>
</div>
<div id="na-action-and-the-data-argument" class="section level3">
<h3 class="hasAnchor">
<a href="#na-action-and-the-data-argument" class="anchor"></a><code>na.action</code> and the <code>data</code> argument</h3>
<p><code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> was written to respect the <code>na.action</code> parameter from the <code>lme4</code> package. This argument defaults to <code>na.omit</code>, which means all rows in the data sets with <code>NA</code>s present are simply deleted from the model. However, there is also an <code>na.exclude</code> option, which pads the resulting tibbles with <code>NA</code>s in the the rows that contained <code>NA</code>s in the original data set in place of deleting them altogether. In order for <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> to do this, the original data set must be passed into <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> via the <code>data</code> argument whenever the <code>na.action</code> was set to <code>na.exclude</code> in the model fitting process.</p>
<p>For example, while the <code>class</code> data set does not have any <code>NA</code>s in the data set, we can introduce a couple for the purposes of an example.</p>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">classNA</span> <span class="op">&lt;-</span> <span class="va">classroom</span>
<span class="va">classNA</span><span class="op">[</span><span class="fl">2</span>,<span class="fl">3</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="cn">NA</span>
<span class="va">classNA</span><span class="op">[</span><span class="fl">3</span>,<span class="fl">4</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="cn">NA</span></code></pre></div>
<p>We can then fit the same model using the <code>lme4</code> package as before. Below, we fit two models, one with <code>na.action = "na.exclude"</code> and one with the default <code>na.action = "na.omit"</code>.</p>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">class.lmer.exclude</span> <span class="op">&lt;-</span> <span class="fu">lme4</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">mathgain</span> <span class="op">~</span> <span class="va">mathkind</span> <span class="op">+</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">minority</span> <span class="op">+</span> <span class="va">ses</span> <span class="op">+</span> <span class="va">housepov</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span><span class="op">|</span><span class="va">schoolid</span><span class="op">/</span><span class="va">classid</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">classNA</span>, na.action <span class="op">=</span> <span class="st">"na.exclude"</span><span class="op">)</span>
<span class="va">class.lmer.omit</span> <span class="op">&lt;-</span> <span class="fu">lme4</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">mathgain</span> <span class="op">~</span> <span class="va">mathkind</span> <span class="op">+</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">minority</span> <span class="op">+</span> <span class="va">ses</span> <span class="op">+</span> <span class="va">housepov</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span><span class="op">|</span><span class="va">schoolid</span><span class="op">/</span><span class="va">classid</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">classNA</span>, na.action <span class="op">=</span> <span class="st">"na.omit"</span><span class="op">)</span></code></pre></div>
<p>We then run <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> on the model where <code>na.action = "na.omit"</code>.</p>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">infl4</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/hlm_influence.default.html">hlm_influence</a></span><span class="op">(</span><span class="va">class.lmer.omit</span>, level <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></code></pre></div>
<pre><code>#&gt; # A tibble: 1,188 x 14
#&gt;       id mathgain mathkind   sex minority   ses housepov schoolid classid
#&gt;    &lt;int&gt;    &lt;int&gt;    &lt;int&gt; &lt;int&gt;    &lt;int&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;int&gt;   &lt;int&gt;
#&gt;  1     1       32      448     1        1  0.46    0.082        1     160
#&gt;  2     2       83      449     0        1 -0.38    0.082        1     217
#&gt;  3     3       53      425     0        1 -0.03    0.082        1     217
#&gt;  4     4       65      450     1        1  0.76    0.082        1     217
#&gt;  5     5       51      452     0        1 -0.03    0.082        1     217
#&gt;  6     6       66      443     0        1  0.2     0.082        1     217
#&gt;  7     7       88      422     1        1  0.64    0.082        1     217
#&gt;  8     8       -7      480     0        1  0.13    0.082        1     217
#&gt;  9     9       60      502     0        1  0.83    0.082        1     217
#&gt; 10    10       -2      502     1        1  0.06    0.082        2     197
#&gt;        cooksd    mdffits covtrace covratio leverage.overall
#&gt;         &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;            &lt;dbl&gt;
#&gt;  1 0.000710   0.000708    0.00351     1.00           0.160 
#&gt;  2 0.000295   0.000294    0.00182     1.00           0.0801
#&gt;  3 0.000140   0.000140    0.00183     1.00           0.0801
#&gt;  4 0.00000818 0.00000815  0.00325     1.00           0.0814
#&gt;  5 0.0000145  0.0000144   0.00124     1.00           0.0795
#&gt;  6 0.00000224 0.00000224  0.00127     1.00           0.0796
#&gt;  7 0.000184   0.000183    0.00400     1.00           0.0821
#&gt;  8 0.00111    0.00111     0.00163     1.00           0.0799
#&gt;  9 0.000375   0.000374    0.00338     1.00           0.0815
#&gt; 10 0.00250    0.00248     0.00508     1.01           0.136 
#&gt; # … with 1,178 more rows</code></pre>
<p>Note than there are only 1,188 rows in the returned tibble, although there were 1,190 observations in the original data set. The two rows with NAs were deleted from the returned tibble.</p>
<p>We repeat this with the model where <code>na.action = "na.exclude"</code>.</p>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"> <span class="va">infl5</span> <span class="op">&lt;-</span><span class="fu"><a href="../reference/hlm_influence.default.html">hlm_influence</a></span><span class="op">(</span><span class="va">class.lmer.exclude</span>, level <span class="op">=</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">classNA</span><span class="op">)</span></code></pre></div>
<pre><code>#&gt; # A tibble: 1,190 x 14
#&gt;       id mathgain mathkind   sex minority   ses housepov schoolid classid
#&gt;    &lt;int&gt;    &lt;int&gt;    &lt;int&gt; &lt;int&gt;    &lt;int&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;int&gt;   &lt;int&gt;
#&gt;  1     1       32      448     1        1  0.46    0.082        1     160
#&gt;  2     2      109       NA     0        1 -0.27    0.082        1     160
#&gt;  3     3       NA      511     1        1 -0.03    0.082        1     160
#&gt;  4     4       83      449     0        1 -0.38    0.082        1     217
#&gt;  5     5       53      425     0        1 -0.03    0.082        1     217
#&gt;  6     6       65      450     1        1  0.76    0.082        1     217
#&gt;  7     7       51      452     0        1 -0.03    0.082        1     217
#&gt;  8     8       66      443     0        1  0.2     0.082        1     217
#&gt;  9     9       88      422     1        1  0.64    0.082        1     217
#&gt; 10    10       -7      480     0        1  0.13    0.082        1     217
#&gt;         cooksd     mdffits covtrace covratio leverage.overall
#&gt;          &lt;dbl&gt;       &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;            &lt;dbl&gt;
#&gt;  1  0.000710    0.000708    0.00351     1.00           0.160 
#&gt;  2 NA          NA          NA          NA             NA     
#&gt;  3 NA          NA          NA          NA             NA     
#&gt;  4  0.000295    0.000294    0.00182     1.00           0.0801
#&gt;  5  0.000140    0.000140    0.00183     1.00           0.0801
#&gt;  6  0.00000818  0.00000815  0.00325     1.00           0.0814
#&gt;  7  0.0000145   0.0000144   0.00124     1.00           0.0795
#&gt;  8  0.00000224  0.00000224  0.00127     1.00           0.0796
#&gt;  9  0.000184    0.000183    0.00400     1.00           0.0821
#&gt; 10  0.00111     0.00111     0.00163     1.00           0.0799
#&gt; # … with 1,180 more rows</code></pre>
<p>In this tibble, there are 1,190 rows. Furthermore, the two rows with NAs display NAs for the influence diagnostics, instead of being entirely absent as in the above example. It is important to note that the <code>data</code> argument is necessary. Failing to provide the data set through the <code>data</code> argument in this situation will result in an error.</p>
</div>
</div>
<div id="hlm_augment-function" class="section level2">
<h2 class="hasAnchor">
<a href="#hlm_augment-function" class="anchor"></a>hlm_augment function</h2>
<p>The <code><a href="../reference/hlm_augment.lmerMod.html">hlm_augment()</a></code> function combines the <code><a href="../reference/hlm_resid.default.html">hlm_resid()</a></code> and <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> functions to return a tibble containing information about the residuals and the influence diagnostics appended to the data. For example, we can obtain residuals and influence diagnostics at once for all students in the <code>class</code> data set with the following:</p>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">aug</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/hlm_augment.lmerMod.html">hlm_augment</a></span><span class="op">(</span><span class="va">class.lmer</span>, level <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></code></pre></div>
<pre><code>#&gt; # A tibble: 1,190 x 20
#&gt;       id mathgain mathkind   sex minority   ses housepov schoolid classid
#&gt;    &lt;dbl&gt;    &lt;int&gt;    &lt;int&gt; &lt;int&gt;    &lt;int&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;int&gt;   &lt;int&gt;
#&gt;  1     1       32      448     1        1  0.46    0.082        1     160
#&gt;  2     2      109      460     0        1 -0.27    0.082        1     160
#&gt;  3     3       56      511     1        1 -0.03    0.082        1     160
#&gt;  4     4       83      449     0        1 -0.38    0.082        1     217
#&gt;  5     5       53      425     0        1 -0.03    0.082        1     217
#&gt;  6     6       65      450     1        1  0.76    0.082        1     217
#&gt;  7     7       51      452     0        1 -0.03    0.082        1     217
#&gt;  8     8       66      443     0        1  0.2     0.082        1     217
#&gt;  9     9       88      422     1        1  0.64    0.082        1     217
#&gt; 10    10       -7      480     0        1  0.13    0.082        1     217
#&gt;     .resid .fitted .ls.resid .ls.fitted .mar.resid .mar.fitted       cooksd
#&gt;      &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt;        &lt;dbl&gt;
#&gt;  1 -37.7      69.7      0          32       -34.6         66.6 0.00106     
#&gt;  2  47.5      61.5      0         109        50.6         58.4 0.00143     
#&gt;  3  18.5      37.5      0          56        21.6         34.4 0.000336    
#&gt;  4  23.3      59.7     35.4        47.6      20.0         63.0 0.000225    
#&gt;  5 -19.9      72.9    -15.4        68.4     -23.1         76.1 0.000173    
#&gt;  6   1.01     64.0     -4.18       69.2      -2.22        67.2 0.000000807 
#&gt;  7  -9.14     60.1     -1.19       52.2     -12.4         63.4 0.0000233   
#&gt;  8   0.413    65.6      4.24       61.8      -2.82        68.8 0.0000000504
#&gt;  9  11.5      76.5      4.18       83.8       8.22        79.8 0.000130    
#&gt; 10 -54.8      47.8    -45.3        38.3     -58.0         51.0 0.00108     
#&gt;         mdffits covtrace covratio leverage.overall
#&gt;           &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;            &lt;dbl&gt;
#&gt;  1 0.00106       0.00289     1.00           0.121 
#&gt;  2 0.00143       0.00246     1.00           0.121 
#&gt;  3 0.000335      0.00378     1.00           0.122 
#&gt;  4 0.000225      0.00169     1.00           0.0780
#&gt;  5 0.000172      0.00178     1.00           0.0780
#&gt;  6 0.000000804   0.00321     1.00           0.0794
#&gt;  7 0.0000233     0.00113     1.00           0.0775
#&gt;  8 0.0000000504  0.00120     1.00           0.0775
#&gt;  9 0.000129      0.00401     1.00           0.0801
#&gt; 10 0.00108       0.00147     1.00           0.0778
#&gt; # … with 1,180 more rows</code></pre>
<p>This is useful for inspecting residuals values and influence diagnostics values at the same time. However, <code><a href="../reference/hlm_augment.lmerMod.html">hlm_augment()</a></code> lacks some of the functionality that <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> and <code><a href="../reference/hlm_resid.default.html">hlm_resid()</a></code> have. The <code>delete</code> and <code>approx</code> parameters available for <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> are not available in <code><a href="../reference/hlm_augment.lmerMod.html">hlm_augment()</a></code>, so the function will always use a one step approximation and delete all observations or groups instead of a selected few. The <code>standardize</code> parameter from <code><a href="../reference/hlm_resid.default.html">hlm_resid()</a></code> is also not included, so <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> or <code><a href="../reference/hlm_resid.default.html">hlm_resid()</a></code> should be used instead if this functionality is desired. For more information about available functionality in <code><a href="../reference/hlm_resid.default.html">hlm_resid()</a></code>, see the <code>hlm_resid</code> vignette.</p>
<p><code><a href="../reference/hlm_augment.lmerMod.html">hlm_augment()</a></code> is especially useful for inspecting residual values of observations with relatively high influence diagnostics values, or vice versa.</p>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">aug2</span> <span class="op">&lt;-</span> <span class="va">aug</span> <span class="op">%&gt;%</span>
  <span class="fu">arrange</span><span class="op">(</span><span class="fu">desc</span><span class="op">(</span><span class="va">cooksd</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>#&gt; # A tibble: 1,190 x 20
#&gt;       id mathgain mathkind   sex minority   ses housepov schoolid classid .resid
#&gt;    &lt;dbl&gt;    &lt;int&gt;    &lt;int&gt; &lt;int&gt;    &lt;int&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;int&gt;   &lt;int&gt;  &lt;dbl&gt;
#&gt;  1   539      253      290     0        1 -0.4     0.257       47      82  110. 
#&gt;  2    41     -110      434     0        1 -0.37    0.365        4     179 -157. 
#&gt;  3  1078      203      290     1        1 -0.32    0.067       95     144   62.0
#&gt;  4   664      -84      629     1        0  2.33    0.17        62      22  -88.7
#&gt;  5   312      138      542     1        0  2.27    0.05        27     104   94.6
#&gt;  6   754      218      368     0        1 -1.14    0.43        70     152  107. 
#&gt;  7   337      197      290     1        1 -0.46    0.214       28     203   60.7
#&gt;  8   723      214      290     1        1 -0.67    0.209       68     244   59.8
#&gt;  9   812      147      510     0        0 -0.47    0.367       75      42   87.2
#&gt; 10  1146       11      376     0        1  0.62    0.126      102      44  -79.8
#&gt;    .fitted .ls.resid .ls.fitted .mar.resid .mar.fitted cooksd mdffits covtrace
#&gt;      &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
#&gt;  1  143.    4.04e+ 1      213.       117.       136.   0.0536  0.0527  0.0172 
#&gt;  2   47.0   0.           -110       -177.        66.8  0.0265  0.0264  0.00406
#&gt;  3  141.    0.            203         65.9      137.   0.0256  0.0250  0.0250 
#&gt;  4    4.67 -2.79e+ 1      -56.1      -81.9       -2.08 0.0245  0.0242  0.0125 
#&gt;  5   43.4  -2.66e-15      138         98.1       39.9  0.0221  0.0219  0.00988
#&gt;  6  111.   -6.66e-15      218        125.        93.1  0.0202  0.0200  0.00702
#&gt;  7  136.    0.            197         62.3      135.   0.0194  0.0190  0.0198 
#&gt;  8  154.    0.            214         80.4      134.   0.0187  0.0183  0.0195 
#&gt;  9   59.8   2.78e+ 1      119.       109.        38.3  0.0148  0.0147  0.00797
#&gt; 10   90.8  -2.60e+ 1       37.0      -91.1      102.   0.0132  0.0131  0.00825
#&gt;    covratio leverage.overall
#&gt;       &lt;dbl&gt;            &lt;dbl&gt;
#&gt;  1     1.02           0.112 
#&gt;  2     1.00           0.143 
#&gt;  3     1.03           0.147 
#&gt;  4     1.01           0.0869
#&gt;  5     1.01           0.0919
#&gt;  6     1.01           0.0896
#&gt;  7     1.02           0.147 
#&gt;  8     1.02           0.155 
#&gt;  9     1.01           0.0722
#&gt; 10     1.01           0.0962
#&gt; # … with 1,180 more rows</code></pre>
<p>We can sort by a particular column in order to inspect the values of other influence diagnostics and the residuals of influential observations.</p>
</div>
<div id="lme-objects-from-nlme-package" class="section level2">
<h2 class="hasAnchor">
<a href="#lme-objects-from-nlme-package" class="anchor"></a>lme objects from nlme package</h2>
<p>Previously, only the individual one step approximation influence functions worked on <code>lme</code> models fit using the <code>nlme</code> package. However, <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> can also be used on <code>lme</code> objects, as can <code><a href="../reference/hlm_augment.lmerMod.html">hlm_augment()</a></code>. This allows the user to calculate influence diagnostics for <code>lme</code> models by fulling refitting the model using the <code>approx = FALSE</code> argument.</p>
<div id="important-differences-for-lme-objects" class="section level3">
<h3 class="hasAnchor">
<a href="#important-differences-for-lme-objects" class="anchor"></a>Important differences for lme objects</h3>
<p>In most cases, using a <code>lme</code> object for <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> or <code><a href="../reference/hlm_augment.lmerMod.html">hlm_augment()</a></code> is identical to their usage with <code>lmerMod</code> objects from <code>lme4</code>. However, there are a few notable exceptions.</p>
<p>For both <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> and <code><a href="../reference/hlm_augment.lmerMod.html">hlm_augment()</a></code>, levels should be specified by names that appear in <code>model@flist</code>. For the second level of a three level <code>lmerMod</code> model, this usually looks like “level2:level3” where level2 and level3 are the names of the second and third level variables, respectively. However, for a <code>lme</code> model, levels should be specified by names that appear in <code>model$groups</code>. For example, we can obtain influence diagnostics for each classroom from the <code>class</code> data set in the following way:</p>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">class.lme</span> <span class="op">&lt;-</span> <span class="fu">nlme</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/nlme/man/lme.html">lme</a></span><span class="op">(</span><span class="va">mathgain</span> <span class="op">~</span> <span class="va">mathkind</span> <span class="op">+</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">minority</span> <span class="op">+</span> <span class="va">ses</span> <span class="op">+</span> <span class="va">housepov</span>, random <span class="op">=</span> <span class="op">~</span> <span class="fl">1</span><span class="op">|</span><span class="va">schoolid</span><span class="op">/</span><span class="va">classid</span>, data <span class="op">=</span> <span class="va">classroom</span><span class="op">)</span>
<span class="fu"><a href="../reference/hlm_influence.default.html">hlm_influence</a></span><span class="op">(</span><span class="va">class.lme</span>, level <span class="op">=</span> <span class="st">"classid"</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 312 x 6</span>
<span class="co">#&gt;    classid   cooksd  mdffits covtrace covratio leverage.overall</span>
<span class="co">#&gt;    &lt;fct&gt;      &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;            &lt;dbl&gt;</span>
<span class="co">#&gt;  1 1/160   0.00224  0.00224   0.00990     1.01           0.121 </span>
<span class="co">#&gt;  2 1/217   0.00133  0.00131   0.0238      1.02           0.0784</span>
<span class="co">#&gt;  3 2/197   0.00323  0.00320   0.0106      1.01           0.126 </span>
<span class="co">#&gt;  4 2/211   0.00724  0.00719   0.0202      1.02           0.102 </span>
<span class="co">#&gt;  5 2/307   0.00346  0.00343   0.0197      1.02           0.0752</span>
<span class="co">#&gt;  6 3/11    0.00116  0.00115   0.0141      1.01           0.102 </span>
<span class="co">#&gt;  7 3/137   0.000873 0.000868  0.0131      1.01           0.0819</span>
<span class="co">#&gt;  8 3/145   0.00517  0.00515   0.0248      1.02           0.107 </span>
<span class="co">#&gt;  9 3/228   0.000479 0.000478  0.00797     1.01           0.148 </span>
<span class="co">#&gt; 10 4/48    0.00371  0.00367   0.0212      1.02           0.149 </span>
<span class="co">#&gt; # … with 302 more rows</span></code></pre></div>
<p>For the <code>lmerMod</code> model, we specified <code>level = classid:schoolid</code>. However, for <code>lme</code> models, the name of the second level alone is sufficient. However, specifying names of specific groups to delete for <code>lme</code> models is also slightly different. For example, we can obtain influence diagnostics for a model created when classes 160 and 217 are deleted for a <code>lmerMod</code> model in the following way:</p>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/hlm_influence.default.html">hlm_influence</a></span><span class="op">(</span><span class="va">class.lmer</span>, level <span class="op">=</span> <span class="st">"classid:schoolid"</span>, delete <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"160:1"</span>, <span class="st">"217:1"</span><span class="op">)</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 1 x 4</span>
<span class="co">#&gt;     cooksd  mdffits covtrace covratio</span>
<span class="co">#&gt;      &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;</span>
<span class="co">#&gt; 1 0.000561 0.000557   0.0381     1.04</span></code></pre></div>
<p>Obtaining influence diagnostics for a model created with the deletion of classes 160 and 217 from a <code>lme</code> model is a bit different:</p>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/hlm_influence.default.html">hlm_influence</a></span><span class="op">(</span><span class="va">class.lme</span>, level <span class="op">=</span> <span class="st">"classid"</span>, delete <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"1/160"</span>, <span class="st">"1/217"</span><span class="op">)</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 1 x 4</span>
<span class="co">#&gt;     cooksd  mdffits covtrace covratio</span>
<span class="co">#&gt;      &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;</span>
<span class="co">#&gt; 1 0.000561 0.000557   0.0381     1.04</span></code></pre></div>
<p>Note that both examples specify units for deletion in the same way they are specified in <code>model@flist</code> (<code>lmerMod</code> models) or <code>model$groups</code> (<code>lme</code> models).</p>
<p>Additionally, <code>lmerMod</code> models require that the <code>data</code> argument is passed into <code><a href="../reference/hlm_influence.default.html">hlm_influence()</a></code> and <code><a href="../reference/hlm_augment.lmerMod.html">hlm_augment()</a></code> when <code>na.action = "na.exclude"</code> during the model fitting process. However, this is unnecessary for <code>lme</code> models.</p>
</div>
</div>
<div id="cooks-distance-values-comparison-to-other-packages" class="section level2">
<h2 class="hasAnchor">
<a href="#cooks-distance-values-comparison-to-other-packages" class="anchor"></a>Cook’s distance values comparison to other packages</h2>
<p>The <code>HLMdiag</code> package has two different ways to calculate Cook’s distance. One of them, which is more exact, refits the model with each observation or group deleted from the model and calculates Cook’s distance from the resulting coefficient estimates and variance components estimates. The second is a one-step approximation. For more information about how the one step approximation works, we refer the reader to <strong>Christensen et.al (1992)</strong>; <strong>Shi and Chen (2008)</strong>; and <strong>Zewotir (2008)</strong>. Other R packages also have functions that can calculate Cook’s distance. In this section, we highlight the differences between the ways of calculating Cook’s distance in <code>HLMdiag</code> versus other methods in the <code>car</code> and <code>lme4</code> packages.</p>
<div id="the-car-package" class="section level3">
<h3 class="hasAnchor">
<a href="#the-car-package" class="anchor"></a>The <code>car</code> package</h3>
<p>The <code>cooks_distance()</code> function from <code>HLMdiag</code> calculates Cook’s distance through a full refit of the model using the following formula:</p>
<p><span class="math inline">\(C_i(\hat{\beta}) = \frac{1}{p}{(\hat{\beta} - \hat{\beta}_{(i)})}^\top\widehat{\mathrm{VAR}(\hat{\beta})}^{-1}(\hat{\beta} - \hat{\beta}_{(i)})\)</span></p>
<p>Notice that the difference in the change in the parameter estimates is scaled by the estimated covariance matrix of the original parameter estimates. We can calculate the Cook’s distance values in the <code>HLMdiag</code> package by first using the <code><a href="../reference/case_delete.default.html">case_delete()</a></code> function, followed by the <code><a href="../reference/mdffits.default.html">cooks.distance()</a></code> function.</p>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">hlm_case</span> <span class="op">&lt;-</span> <span class="fu">HLMdiag</span><span class="fu">:::</span><span class="fu"><a href="../reference/case_delete.default.html">case_delete.lmerMod</a></span><span class="op">(</span><span class="va">class.lmer</span><span class="op">)</span>
<span class="va">hlm_cd_full</span> <span class="op">&lt;-</span> <span class="fu">HLMdiag</span><span class="fu">:::</span><span class="fu"><a href="../reference/diagnostics.html">cooks.distance.case_delete</a></span><span class="op">(</span><span class="va">hlm_case</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">hlm_cd_full</span><span class="op">)</span>
<span class="co">#&gt; [1] 9.327238e-04 1.415243e-03 3.316859e-04 2.282399e-04 1.797497e-04</span>
<span class="co">#&gt; [6] 6.968432e-07</span></code></pre></div>
<p>Conversely, the <code><a href="../reference/mdffits.default.html">mdffits()</a></code> function from <code>HLMdiag</code> calculates MDFFITS, which is a multivariate version of the DFFITS statistic. This is calculated as follows:</p>
<p><span class="math inline">\(MDFFITS_i(\hat{\beta}) = \frac{1}{p}{(\hat{\beta} - \hat{\beta}_{(i)})}^\top\widehat{\mathrm{VAR}(\hat{\beta}_{(i)})}^{-1}(\hat{\beta} - \hat{\beta}_{(i)})\)</span></p>
<p>Instead of scaling by the estimated covariance matrix of the original parameter estimates, calculations for MDFFITS are scaled by the estimated covariance matrix of the deletion estimates. For each deleted observation or group, the model is refit and the covariance structure re-estimated without unit <em>i</em>. We can calculate this similarly to how we calculated Cook’s distance, using the same <code>case_delete</code> object.</p>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">hlm_mdffits</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/mdffits.default.html">mdffits</a></span><span class="op">(</span><span class="va">hlm_case</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">hlm_mdffits</span><span class="op">)</span>
<span class="co">#&gt; [1] 9.304263e-04 1.412796e-03 3.302360e-04 2.278198e-04 1.793468e-04</span>
<span class="co">#&gt; [6] 6.942264e-07</span></code></pre></div>
<p>These estimates are pretty similar to those produced by <code>cooks_distance()</code>; the difference is due to the use of the covariance matrix of the deletion estimates, rather than the original estimates.</p>
<p>The <code>car</code> package calculates Cook’s distance similarly to how the <code>HLMdiag</code> package calculates MDFFITS. Instead of using the covariance matrix of the original parameter estimates like <code>HLMdiag</code>’s <code>cooks_distance()</code> function, the <code><a href="../reference/mdffits.default.html">cooks.distance()</a></code> function from <code>car</code> uses the estimated covariance matrix of the deletion estimates. However, the <code>cooks_distance()</code> function from car is not identical to the <code>mdffits</code> function from <code>HLMdiag</code>; the <code>car::cooks.distance()</code> function also scaled each observation, <em>i</em>, by dividing it by the estimated variance of the model calculated without observation <em>i</em>. Therefore, the formula used to calculate Cook’s distance in the <code>car</code> package is as follows:</p>
<p><span class="math inline">\(C_i(\hat{\beta}) = \frac{1}{p\hat{\sigma_{i}}^2}{(\hat{\beta} - \hat{\beta}_{(i)})}^\top\widehat{\mathrm{VAR}(\hat{\beta}_{(i)})}^{-1}(\hat{\beta} - \hat{\beta}_{(i)})\)</span></p>
<p>We can calculate this by first using the <code><a href="https://rdrr.io/r/stats/lm.influence.html">influence()</a></code> function followed by the <code><a href="../reference/mdffits.default.html">cooks.distance()</a></code> function.</p>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-forge.r-project.org/projects/car/">car</a></span><span class="op">)</span>
<span class="va">car_case</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.influence.html">influence</a></span><span class="op">(</span><span class="va">class.lmer</span><span class="op">)</span> 
<span class="va">car_cd</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/mdffits.default.html">cooks.distance</a></span><span class="op">(</span><span class="va">car_case</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">car_cd</span><span class="op">)</span>
<span class="co">#&gt; [1] 1.270970e-06 1.928339e-06 4.493427e-07 3.102931e-07 2.441009e-07</span>
<span class="co">#&gt; [6] 9.411194e-10</span></code></pre></div>
<p>These values initially seem fairly different from the MDFFITS and Cook’s distance values produced by <code>HLMdiag</code>, due to the additional scaling by the inverse of the variance of each refitted model. We can adjust for this by multiplying the vector of Cook’s distance values from <code>car</code> by the estimated variance from each refitted model.</p>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sig.sq</span> <span class="op">&lt;-</span> <span class="va">car_case</span><span class="op">[[</span><span class="fl">4</span><span class="op">]</span><span class="op">]</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span>
<span class="va">car_cd_adjusted</span> <span class="op">&lt;-</span> <span class="va">car_cd</span> <span class="op">*</span> <span class="va">sig.sq</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">car_cd_adjusted</span><span class="op">)</span>
<span class="co">#&gt;            1            2            3            4            5            6 </span>
<span class="co">#&gt; 9.304279e-04 1.412774e-03 3.302267e-04 2.278159e-04 1.793900e-04 6.918772e-07</span></code></pre></div>
<p>Once the values from <code>car</code> have been adjusted by sigma squared, they now appear very similar to the MDFFITS values from <code>HLMdiag</code>. The plot below shows the difference between the MDFFITS estimates from <code>HLMdiag</code> and the variance-adjusted Cook’s distance estimates from <code>car</code> for all 1,190 observations in the <code>classroom</code> data set.</p>
<p>While the difference between the estimates varies slightly due to differences in how the fixed effects and variance components are calculated for refit models in both packages, the difference in values tends to be very small.</p>
</div>
<div id="the-lme4-package" class="section level3">
<h3 class="hasAnchor">
<a href="#the-lme4-package" class="anchor"></a>The <code>lme4</code> package</h3>
<p>Similar to <code>HLMdiag</code>, the <code>lme4</code> package has two methods that calculate Cook’s distance. One of them, similar to the <code>case_delete</code> method, conducts a full refit of models without each observation or group. The second is a quicker approximation.</p>
<div id="lme4-approximation" class="section level4">
<h4 class="hasAnchor">
<a href="#lme4-approximation" class="anchor"></a><code>lme4</code> approximation</h4>
<p>In order to calculate the approximation of Cook’s distance values from <code>lme4</code>, we use the <code><a href="../reference/mdffits.default.html">cooks.distance()</a></code> function.</p>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">lme_cd_approx</span> <span class="op">&lt;-</span> <span class="fu">lme4</span><span class="fu">:::</span><span class="fu"><a href="https://rdrr.io/pkg/lme4/man/influence.merMod.html">cooks.distance.merMod</a></span><span class="op">(</span><span class="va">class.lmer</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">lme_cd_approx</span><span class="op">)</span>
<span class="co">#&gt;           1           2           3           4           5           6 </span>
<span class="co">#&gt; 0.050602009 0.080124360 0.012322170 0.011276222 0.008216468 0.000021657</span></code></pre></div>
<p>However, this approximation is fairly different from the one produced from <code>HLMdiag</code>.</p>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">hlm_cd_approx</span> <span class="op">&lt;-</span> <span class="fu">HLMdiag</span><span class="fu">:::</span><span class="fu"><a href="../reference/mdffits.default.html">cooks.distance.lmerMod</a></span><span class="op">(</span><span class="va">class.lmer</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">hlm_cd_approx</span><span class="op">)</span>
<span class="co">#&gt; [1] 1.060728e-03 1.433652e-03 3.358071e-04 2.249644e-04 1.726769e-04</span>
<span class="co">#&gt; [6] 8.069538e-07</span></code></pre></div>
<p>The approximation from <code>HLMdiag</code> is also closer to the full refit calculated by <code>HLMdiag</code> than the <code>lme4</code> approximation is. The plots below show the difference between the full refit from <code>HLMdiag</code> and the <code>HLMdiag</code> approximation (left) and the <code>lme4</code> approximation (right).</p>
<p>The estimates produced by the <code>lme4</code> approximation are never smaller than the values from the <code>HLMdiag</code> full refit, but they tend to be further off the <code>HLMdiag</code> full refit values than the <code>HLMdiag</code> approximation values are. The difference between the full refit and the approximation from <code>HLMdiag</code> tends to be very small (&lt; 0.0005), while the difference between the full refit and the <code>lme4</code> approximation values tends to be much larger.</p>
</div>
<div id="lme4-full-refit" class="section level4">
<h4 class="hasAnchor">
<a href="#lme4-full-refit" class="anchor"></a><code>lme4</code> full refit</h4>
<p><code>lme4</code> also has a function that performs a full refit of the models without each observation or group and calculates Cook’s distance values based off those refits. We can calculate this by using the <code>influence</code> function from <code>lme4</code>.</p>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">lme_case</span> <span class="op">&lt;-</span> <span class="fu">lme4</span><span class="fu">:::</span><span class="fu"><a href="https://rdrr.io/pkg/lme4/man/influence.merMod.html">influence.merMod</a></span><span class="op">(</span><span class="va">class.lmer</span>, data <span class="op">=</span> <span class="va">classroom</span><span class="op">)</span> 
<span class="va">cd_lme_full</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/mdffits.default.html">cooks.distance</a></span><span class="op">(</span><span class="va">lme_case</span><span class="op">)</span> </code></pre></div>
<p><code>lme4</code>’s cook’s distance function for objects created from the <code>influence</code> function has a bug that prevents us from obtaining Cook’s distance values from the <code>influence</code> object using <code>lme4</code>; however, we can use the <code>cooks.distance</code> function from the <code>stats</code> package on the <code>influence</code> object from <code>lme4</code>.</p>
<p>The values obtained from <code>lme4</code> match those from <code>car</code>, meaning that <code>lme4</code> is also scaling the estimates by dividing by the estimated variance of each refit model, in addition to using the estimated covariance matrix from the deletion estimates, rather than the original estimates. Therefore, the <code>lme4</code> package is also using this formula to calculate Cook’s distance:</p>
<p><span class="math inline">\(C_i(\hat{\beta}) = \frac{1}{p\hat{\sigma_{i}}^2}{(\hat{\beta} - \hat{\beta}_{(i)})}^\top\widehat{\mathrm{VAR}(\hat{\beta}_{(i)})}^{-1}(\hat{\beta} - \hat{\beta}_{(i)})\)</span></p>
<p>The full refits from the <code>lme4</code> and <code>car</code> packages both choose to calculate what is MDFFITS in the <code>HLMdiag</code> package, and additionally choose to scale by dividing by the variance from each refit model. Those choices explain almost all of the differences between Cook’s distance values from the three different packages; additional variation is due to differences in how the new models are fit and coefficients estimated.</p>
<p>##References Bates D, Maechler M, Bolker B, Walker S (2015). Fitting Linear Mixed-Effects Models Using lme4. Journal of Statistical Software, 67(1), 1-48. URL <a href="http://dx.doi.org/10.18637/jss.v056.i05" class="uri">http://dx.doi.org/10.18637/jss.v056.i05</a></p>
<p>Christensen R, Pearson L, Johnson W (1992). “Case-Deletion Diagnostics for Mixed Models.” <em>Technometrics</em>, 34(1), 38–45.</p>
<p>Fox J, Weisburg S (2019). A {R} Companion to Applied Regression, Third Addition. Thousand Oaks CA: Sage. URL: <a href="https://socialsciences.mcmaster.ca/jfox/Books/Companion/" class="uri">https://socialsciences.mcmaster.ca/jfox/Books/Companion/</a></p>
<p>Loy A, Hofmann H (2014). HLMdiag: A Suite of Diagnostics for Hierarchical Linear Models in R. <em>Journal of Statistical Software</em>, 56(5), 1-28.</p>
<p>Pinheiro J, Bates D, DebRoy S, Sarkar D, R Core Team (2020). <em>nlme: Linear and Nonlinear Mixed Effects Models</em>. R package version 3.1-148, &lt;URL: <a href="https://CRAN.R-project.org/package=nlme" class="uri">https://CRAN.R-project.org/package=nlme</a>&gt;.</p>
<p>Shi L, Chen G (2008). “Case Deletion Diagnostics in Multilevel Models.” <em>Journal of Multivariate Analysis</em>, 99(9), 1860–1877.</p>
<p>West, B., Welch, K. &amp; Galecki, A. (2006) Linear Mixed Models: A Practical Guide Using Statistical Software. First Edition. Chapman Hall / CRC Press. ISBN 1584884800</p>
<p>Zewotir T (2008). “Multiple Cases Deletion Diagnostics for Linear Mixed Models.” <em>Communications in Statistics – Theory and Methods</em>, 37(7), 1071–1084.</p>
</div>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Adam Loy, Jaylin Lowe, Jack Moran.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
